services:
  postgres:
    container_name: serveAe-api
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: serveAe
    volumes:
      - ./data/pg:/var/lib/postgresql/data
